<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>惠配通Android APP 回归测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { word-wrap: break-word; word-break: break-all; overflow: auto; }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>惠配通Android APP 回归测试报告</h1>
<p class='attribute'><strong>Start Time:</strong> 2016-09-29 13:48:49</p>
<p class='attribute'><strong>Duration:</strong> 0:29:24.995126</p>
<p class='attribute'><strong>Status:</strong> Pass 37 Failure 1 Error 40</p>

<p class='description'>惠配通Android APP 回归测试报告</p>
</div>



<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
    <td>Screenshot</td>

</tr>

<tr class='errorClass'>
    <td>test1_firstpage.TestFirstPage</td>
    <td>22</td>
    <td>2</td>
    <td>0</td>
    <td>20</td>
    <td><a href="javascript:showClassDetail('c1',22)">Detail</a></td>
    <td>&nbsp;</td>
</tr>

<tr id='pt1.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_1Login: 使用手机号密码登录</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt1.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_CommingMsgCenter: 进入消息中心页面-商品通知</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='ft1.3' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommingMsgCenter_sysnotice: 进入消息中心页面-系统通知</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.3')" >
        error</a>

    <div id='div_ft1.3' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.3: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 150, in test_CommingMsgCenter_sysnotice
    self.myassert.assertEw(self.first.first_pge, '首页元素不存在')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: UiAutomator died while responding to command, please check appium logs!

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 150, in test_CommingMsgCenter_sysnotice
    self.myassert.assertEw(self.first.first_pge, '首页元素不存在')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: UiAutomator died while responding to command, please check appium logs!



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.4' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommingMsgCenter_sysnotice: 进入消息中心页面-系统通知</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.4')" >
        error</a>

    <div id='div_ft1.4' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.4: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.5' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommingRollCenter: 进入领卷中心--我的优惠卷页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.5')" >
        error</a>

    <div id='div_ft1.5' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.5').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.5: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 113, in test_CommingRollCenter
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 113, in test_CommingRollCenter
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.6' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommingRollCenter: 进入领卷中心--我的优惠卷页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.6')" >
        error</a>

    <div id='div_ft1.6' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.6').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.6: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.7' class='none'>
    <td class='errorCase'><div class='testcase'>test_RollCenterH5: 查看领卷中心--品牌现金卷</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.7')" >
        error</a>

    <div id='div_ft1.7' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.7: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 102, in test_RollCenterH5
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 102, in test_RollCenterH5
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.8' class='none'>
    <td class='errorCase'><div class='testcase'>test_RollCenterH5: 查看领卷中心--品牌现金卷</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.8')" >
        error</a>

    <div id='div_ft1.8' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.8').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.8: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.9' class='none'>
    <td class='errorCase'><div class='testcase'>test_drink: 从首页进入饮料分类列表</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.9')" >
        error</a>

    <div id='div_ft1.9' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.9').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.9: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 90, in test_drink
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 90, in test_drink
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.10' class='none'>
    <td class='errorCase'><div class='testcase'>test_drink: 从首页进入饮料分类列表</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.10')" >
        error</a>

    <div id='div_ft1.10' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.10').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.10: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.11' class='none'>
    <td class='errorCase'><div class='testcase'>test_fast_food: 从首页进入方便速食分类列表</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.11')" >
        error</a>

    <div id='div_ft1.11' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.11').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.11: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 96, in test_fast_food
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 96, in test_fast_food
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.12' class='none'>
    <td class='errorCase'><div class='testcase'>test_fast_food: 从首页进入方便速食分类列表</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.12')" >
        error</a>

    <div id='div_ft1.12' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.12').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.12: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.13' class='none'>
    <td class='errorCase'><div class='testcase'>test_first_recharge: 从首页进入充值页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.13')" >
        error</a>

    <div id='div_ft1.13' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.13').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.13: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 84, in test_first_recharge
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 84, in test_first_recharge
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.14' class='none'>
    <td class='errorCase'><div class='testcase'>test_first_recharge: 从首页进入充值页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.14')" >
        error</a>

    <div id='div_ft1.14' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.14').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.14: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.15' class='none'>
    <td class='errorCase'><div class='testcase'>test_first_search: 从首页进入搜索页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.15')" >
        error</a>

    <div id='div_ft1.15' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.15').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.15: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 72, in test_first_search
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 72, in test_first_search
    self.myassert.assertEw(self.first.first_pge, '首页加载失败')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.16' class='none'>
    <td class='errorCase'><div class='testcase'>test_first_search: 从首页进入搜索页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.16')" >
        error</a>

    <div id='div_ft1.16' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.16').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.16: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.17' class='none'>
    <td class='errorCase'><div class='testcase'>test_msg_center: 点击消息中心按钮进入消息中心</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.17')" >
        error</a>

    <div id='div_ft1.17' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.17').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.17: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 78, in test_msg_center
    self.myassert.assertEw(self.first.msg_button, '消息中心无消息')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 78, in test_msg_center
    self.myassert.assertEw(self.first.msg_button, '消息中心无消息')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.18' class='none'>
    <td class='errorCase'><div class='testcase'>test_msg_center: 点击消息中心按钮进入消息中心</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.18')" >
        error</a>

    <div id='div_ft1.18' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.18').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.18: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.19' class='none'>
    <td class='errorCase'><div class='testcase'>test_new_good_more: 新品上市-查看更多</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.19')" >
        error</a>

    <div id='div_ft1.19' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.19').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.19: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 167, in test_new_good_more
    self.myassert.assertEw(self.first.first_pge, '首页元素不存在')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 167, in test_new_good_more
    self.myassert.assertEw(self.first.first_pge, '首页元素不存在')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.20' class='none'>
    <td class='errorCase'><div class='testcase'>test_new_good_more: 新品上市-查看更多</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.20')" >
        error</a>

    <div id='div_ft1.20' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.20').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.20: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.21' class='none'>
    <td class='errorCase'><div class='testcase'>test_newgood_detail: 从新品上市推荐商品中进入商品详情</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.21')" >
        error</a>

    <div id='div_ft1.21' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.21').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.21: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 161, in test_newgood_detail
    self.myassert.assertEw(self.first.first_pge, '首页元素不存在')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 161, in test_newgood_detail
    self.myassert.assertEw(self.first.first_pge, '首页元素不存在')
  File "G:\huipeitongUI\assection\assection.py", line 24, in assertEw
    self.assertTrue(self.current.elementwait(loc), self.driver, errorinfo)
  File "G:\huipeitongUI\po\basepage.py", line 150, in elementwait
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "G:\huipeitongUI\po\basepage.py", line 150, in &lt;lambda&gt;
    WebDriverWait(self._mydriver, 60, 1).until(lambda x: x.find_element(loc[0], loc[1]).is_displayed())
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft1.22' class='none'>
    <td class='errorCase'><div class='testcase'>test_newgood_detail: 从新品上市推荐商品中进入商品详情</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.22')" >
        error</a>

    <div id='div_ft1.22' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft1.22').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft1.22: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 51, in tearDown
    self.driver.start_activity('com.huimin.ordersystem', 'com.huimin.ordersystem.activity.WelcomeActivity')
  File "C:\python35\lib\site-packages\appium\webdriver\webdriver.py", line 572, in start_activity
    self.execute(Command.START_ACTIVITY, data)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr class='errorClass'>
    <td>unittest.suite._ErrorHolder</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>1</td>
    <td><a href="javascript:showClassDetail('c2',1)">Detail</a></td>
    <td>&nbsp;</td>
</tr>

<tr id='ft2.1' class='none'>
    <td class='errorCase'><div class='testcase'>TestFirstPage)</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        error</a>

    <div id='div_ft2.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft2.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft2.1: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 42, in tearDownClass
    self.driver.quit()
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in quit
    self.execute(Command.QUIT)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test1_firstpage.py", line 42, in tearDownClass
    self.driver.quit()
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in quit
    self.execute(Command.QUIT)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr class='errorClass'>
    <td>test2_orderpage.TestOrderPage</td>
    <td>22</td>
    <td>18</td>
    <td>1</td>
    <td>3</td>
    <td><a href="javascript:showClassDetail('c3',22)">Detail</a></td>
    <td>&nbsp;</td>
</tr>

<tr id='ft3.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_CheckGoodsDetails: 从商品列表进入商品详情页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.1')" >
        error</a>

    <div id='div_ft3.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.1: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 88, in test_CheckGoodsDetails
    name=i.get_attribute('name')
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 111, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 88, in test_CheckGoodsDetails
    name=i.get_attribute('name')
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 111, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='pt3.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_CheckLeftView: 查看左侧分类列表有无商品</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_GoodsDetailsBackSearch: 从搜索商品详情页返回至搜索列表页</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_GoodsDetailsCollect: 商品详情页收藏商品</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_GoodsDetailsPicture: 商品详情页——图文详情</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_GoodsDetailsShopCar: 从商品详情页进入购物车页面(购物车为空)</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='ft3.7' class='none'>
    <td class='errorCase'><div class='testcase'>test_GoodsDetailsShopCarAdds: 从商品详情页进入购物车页面(购物车不为空)</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.7')" >
        error</a>

    <div id='div_ft3.7' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.7: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 329, in test_GoodsDetailsShopCarAdds
    self.first.click_add()
  File "G:\huipeitongUI\po\firstpage.py", line 227, in click_add
    self.find_element(self.add).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 329, in test_GoodsDetailsShopCarAdds
    self.first.click_add()
  File "G:\huipeitongUI\po\firstpage.py", line 227, in click_add
    self.find_element(self.add).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='pt3.8' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_GoodsdetailBackupKeepList: 商品详情页返回至常购清单页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='ft3.9' class='none'>
    <td class='errorCase'><div class='testcase'>test_GoodsdetailsShopCarAdd: 从商品详情页添加商品至加入购物车</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.9')" >
        error</a>

    <div id='div_ft3.9' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.9').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.9: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 293, in test_GoodsdetailsShopCarAdd
    self.first.click_add()
  File "G:\huipeitongUI\po\firstpage.py", line 227, in click_add
    self.find_element(self.add).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 293, in test_GoodsdetailsShopCarAdd
    self.first.click_add()
  File "G:\huipeitongUI\po\firstpage.py", line 227, in click_add
    self.find_element(self.add).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='pt3.10' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_KeepList: 进入常购清单页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.11' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_KeepListGoodsdetails: 进入常购清单——商品详情页</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='ft3.12' class='none'>
    <td class='failCase'><div class='testcase'>test_KeepListShopCarAdd: 进入常购清单——添加购物车</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.12')" >
        fail</a>

    <div id='div_ft3.12' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft3.12').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft3.12: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 373, in test_KeepListShopCarAdd
    self.myassert.assertt(nums==2,'添加购物车失败')
  File "G:\huipeitongUI\assection\assection.py", line 12, in assertt
    self.assertTrue(loc, self.driver, errorinfo)
AssertionError: False is not true
 : 添加购物车失败
Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test2_orderpage.py", line 373, in test_KeepListShopCarAdd
    self.myassert.assertt(nums==2,'添加购物车失败')
  File "G:\huipeitongUI\assection\assection.py", line 12, in assertt
    self.assertTrue(loc, self.driver, errorinfo)
AssertionError: False is not true
 : 添加购物车失败


        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="http://192.168.100.23:8081/screenshot/16-09-29_13_58_10.png" title="http://192.168.100.23:8081/screenshot/16-09-29_13_58_10.png ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='pt3.13' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_Search: 进入搜索商品页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.14' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchBackOrderPage: 从搜索页面返回至惠民订货页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.15' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchGoods: 搜索商品-"统一"</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.16' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchGoodsAddShopCar: 从搜索结果页加入购物车</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.17' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchGoodsDetails: 从搜索结果页进入商品详情</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.18' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchGoodsHotBuy: 搜索页面——火热购买——商品详情</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.19' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchGoodsHotBuySwipe: 搜索页面——滑动火热购买商品</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.20' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SearchGoodsNull: 搜索商品—“%@！”</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.21' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_ShopCarAdd: 惠民订货页添加商品至购物车(输入数字)</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt3.22' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_ShopCarUpdateGoods: 惠民订货页面增加、减少购物车商品数量(+-)</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr class='errorClass'>
    <td>test3_shopping_cart.TestShoppingCar</td>
    <td>16</td>
    <td>0</td>
    <td>0</td>
    <td>16</td>
    <td><a href="javascript:showClassDetail('c4',16)">Detail</a></td>
    <td>&nbsp;</td>
</tr>

<tr id='ft4.1' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommitOrder_pp_tickets: 提交订单页面点击品牌现金卷</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.1')" >
        error</a>

    <div id='div_ft4.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.1: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 253, in test_CommitOrder_pp_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 253, in test_CommitOrder_pp_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.2' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommitOrder_shw_tickets: 提交订单页面点击实物卷</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.2')" >
        error</a>

    <div id='div_ft4.2' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.2').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.2: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 234, in test_CommitOrder_shw_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 234, in test_CommitOrder_shw_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.3' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommitOrder_wx_tickets: 提交订单页面点击品牌现金卷</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.3')" >
        error</a>

    <div id='div_ft4.3' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.3').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.3: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 272, in test_CommitOrder_wx_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 272, in test_CommitOrder_wx_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.4' class='none'>
    <td class='errorCase'><div class='testcase'>test_CommitOrder_xj_tickets: 提交订单页面点击品牌现金卷</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.4')" >
        error</a>

    <div id='div_ft4.4' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.4').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.4: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 292, in test_CommitOrder_xj_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 292, in test_CommitOrder_xj_tickets
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.5' class='none'>
    <td class='errorCase'><div class='testcase'>test_commitOrder_backup_shopcar: 提交订单页面返回至购物车页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.5')" >
        error</a>

    <div id='div_ft4.5' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.5').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.5: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 338, in test_commitOrder_backup_shopcar
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 338, in test_commitOrder_backup_shopcar
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.6' class='none'>
    <td class='errorCase'><div class='testcase'>test_payOrder: 余额支付订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.6')" >
        error</a>

    <div id='div_ft4.6' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.6').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.6: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 120, in test_payOrder
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 120, in test_payOrder
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.7' class='none'>
    <td class='errorCase'><div class='testcase'>test_payOrderhdf: 货到付款</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.7')" >
        error</a>

    <div id='div_ft4.7' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.7').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.7: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 190, in test_payOrderhdf
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 190, in test_payOrderhdf
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.8' class='none'>
    <td class='errorCase'><div class='testcase'>test_payOrderwx: 进入微信支付页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.8')" >
        error</a>

    <div id='div_ft4.8' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.8').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.8: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 170, in test_payOrderwx
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 170, in test_payOrderwx
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.9' class='none'>
    <td class='errorCase'><div class='testcase'>test_payOrderzfb: 进入支付宝支付页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.9')" >
        error</a>

    <div id='div_ft4.9' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.9').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.9: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 149, in test_payOrderzfb
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 149, in test_payOrderzfb
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.10' class='none'>
    <td class='errorCase'><div class='testcase'>test_payorder_backup_shopcar: 支付选择页面返回至购物车页面</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.10')" >
        error</a>

    <div id='div_ft4.10' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.10').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.10: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 354, in test_payorder_backup_shopcar
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 354, in test_payorder_backup_shopcar
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.11' class='none'>
    <td class='errorCase'><div class='testcase'>test_payorder_comment: 提交订单页面填写备注支付</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.11')" >
        error</a>

    <div id='div_ft4.11' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.11').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.11: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 312, in test_payorder_comment
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 312, in test_payorder_comment
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.12' class='none'>
    <td class='errorCase'><div class='testcase'>test_shopCarGoodsdetails: 从购物车页面进入商品详情页</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.12')" >
        error</a>

    <div id='div_ft4.12' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.12').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.12: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 215, in test_shopCarGoodsdetails
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 215, in test_shopCarGoodsdetails
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.13' class='none'>
    <td class='errorCase'><div class='testcase'>test_shopCarRecommend: 进入购物车推荐商品详情页</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.13')" >
        error</a>

    <div id='div_ft4.13' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.13').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.13: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 228, in test_shopCarRecommend
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 228, in test_shopCarRecommend
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.14' class='none'>
    <td class='errorCase'><div class='testcase'>test_shopCarUpdate: 增加、减少购物车中商品数量</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.14')" >
        error</a>

    <div id='div_ft4.14' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.14').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.14: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 95, in test_shopCarUpdate
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 95, in test_shopCarUpdate
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.15' class='none'>
    <td class='errorCase'><div class='testcase'>test_shopGoodsDel: 删除商品</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.15')" >
        error</a>

    <div id='div_ft4.15' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.15').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.15: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 72, in test_shopGoodsDel
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 72, in test_shopGoodsDel
    self.public.shopCarClear()
  File "G:\huipeitongUI\po\public.py", line 43, in shopCarClear
    self.shopcar.click_del_goods()
  File "G:\huipeitongUI\po\shopcarpage.py", line 68, in click_del_goods
    self.find_element(self.del_goods).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr id='ft4.16' class='none'>
    <td class='errorCase'><div class='testcase'>test_shopGoodsDelone: '-'号删除商品</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.16')" >
        error</a>

    <div id='div_ft4.16' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_ft4.16').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
ft4.16: Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 54, in test_shopGoodsDelone
    ''''-'号删除商品'''
  File "G:\huipeitongUI\po\public.py", line 44, in shopCarClear
    self.shopcar.click_clear_shopcar()
  File "G:\huipeitongUI\po\shopcarpage.py", line 72, in click_clear_shopcar
    self.find_element(self.clear_shopcar).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Traceback (most recent call last):
  File "G:\huipeitongUI\testcase\test3_shopping_cart.py", line 54, in test_shopGoodsDelone
    ''''-'号删除商品'''
  File "G:\huipeitongUI\po\public.py", line 44, in shopCarClear
    self.shopcar.click_clear_shopcar()
  File "G:\huipeitongUI\po\shopcarpage.py", line 72, in click_clear_shopcar
    self.find_element(self.clear_shopcar).click()
  File "G:\huipeitongUI\po\basepage.py", line 15, in find_element
    return self._mydriver.find_element(loc[0],loc[1])
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.



        </pre>
    </div>
    <!--css div popup end-->

    </td>
    <td align='center'>
    <a target="_blank" href="" title=" ">
    <img src="..\img.png" height=15 width=15 border=0 /></a>
    </td>
</tr>

<tr class='passClass'>
    <td>test4_business_center.TestBusinessCenter</td>
    <td>17</td>
    <td>17</td>
    <td>0</td>
    <td>0</td>
    <td><a href="javascript:showClassDetail('c5',17)">Detail</a></td>
    <td>&nbsp;</td>
</tr>

<tr id='pt5.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_Coupon: 进入优惠卷页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.2' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_JoinStore: 合作店铺</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.3' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_LogOut: 退出登录</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.4' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_MemberPoints: 进入积分查询页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.5' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_MsgCenter: 进入消息中心页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.6' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_OrderManage: 订单管理</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.7' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_PrepaidZFB: 进入账户余额-支付宝充值页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.8' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_ServiceTel: 客服电话</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.9' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_SettingUp: 进入设置页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.10' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_TradingRecord: 进入交易记录页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.11' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_getcoupon: 账户余额——领卷</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.12' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_mycollect</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.13' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_mycollect_goodsdetail: 我的收藏页面--商品详情页</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.14' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_mycollect_shopcaradd: 我的收藏页面加入购物车</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.15' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_prepaidWX: 进入账户余额-微信充值页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.16' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_prepaid_detail: 账户余额-余额明细页面</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='pt5.17' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_reward_detail: 账户余额-奖励明细</div></td>
    <td colspan='5' align='center'>pass</td>
    <td></td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>78</td>
    <td>37</td>
    <td>1</td>
    <td>40</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

</body>
</html>
